apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-blackbox-lq7q2-data-infra
  namespace: blackbox
  labels:
    app.kubernetes.io/name: kube-blackbox
    app.kubernetes.io/instance: kube-blackbox-lq7q2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
